#!/bin/bash
#
# Cross-compile for all architectures and platforms.

set -e

if ! which gox >/dev/null 2>&1 ; then
  echo "Installing gox."
  go get github.com/mitchellh/gox
  echo "Building the gox toolchain."
  gox -build-toolchain
  echo "One-time gox setup is complete."
fi

gox
