#!/bin/bash
#
# Publish build artifacts (binaries and SHA1 checksum files) to Cloud Files
# Pre-requisites/input:
# - RAX_API_KEY contains API key of Rackspace Cloud account where build artifacts
#   are to be published.

set -e

ROOT=$(dirname $0)/..
cd ${ROOT}

# "Constants", LOL
RAX_USERNAME=drgsites
RAX_REGION=IAD
CONTAINER_NAME=cs-reboot-info
IDENTITY_URL=https://identity.api.rackspacecloud.com/v2.0
CF_API_URL=https://storage101.iad3.clouddrive.com/v1/MossoCloudFS_a4792cf6-5b6e-49ea-b7d6-fe4fb7856b6f

# Auth
response=$(curl -s -X POST $IDENTITY_URL/tokens \
    -H 'Content-Type: application/json' \
    -d '{ "auth": { "RAX-KSKEY:apiKeyCredentials": { "username":"'$RAX_USERNAME'", "apiKey": "'$RAX_API_KEY'"}}}' | python -mjson.tool)

token=$(echo "$response" | grep -A5 token | grep id | awk -F\" '{print $4}')
cf_api_url=$(echo "$response" | grep -i mosso | grep -i $RAX_REGION | grep -i publicURL | grep -v cdn | awk -F\" '{print $4}')

# Determine app version
app_version=$(grep 'appVer\s*=' main.go | awk -F\" '{print $2}')

# Upload
for f in bin/cs-reboot-info_*; do
    echo "Publishing $f..."
    g=$(basename $f)
    curl -s -X PUT -s $CF_API_URL/$CONTAINER_NAME/releases/$app_version/$g \
	-H 'X-Auth-Token: '$token \
	--data-binary @$f
done
