#!/bin/bash

set -e

ROOT=$(dirname $0)/..
cd ${ROOT}

if [ -z ${RAX_API_KEY} ]; then
  echo "You must provide RAX_API_KEY to publish."
  exit 1
fi

git pull
script/cross
script/checksum
script/publish
